# CRIMES ANALYSIS
En este notebook se va a documentar los procesos necesarios para realizarle un EDA al dataset con el objetivo de adecuar los datos y limpiarlos para entrenar un modelo mediante machine learning basandose en estos datos.

## ¿DE QUE TRATA EL DATASET?
Este dataset guarda informacion de **757141** casos de crimentes sucedidos en Los Angeles, revelando informacion relevante sobre estos desde **informacion** de la **victima** hasta el contexto del crimen, **que armas** se usaron, **que delito/s** se llevaron a cabo, **donde** sucedio exactamente, etc....

# 1. Importe de librerias

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mutual_info_score
print('Librerías cargadas correctamente')

Librerías cargadas correctamente

# 2. Carga del Dataset

## URL de dataset:
 * #### https://www.kaggle.com/datasets/venkatsairo4899/los-angeles-crime-data-2020-2023?select=Crime_Data_from_2020_to_Present.csv

In [3]:
#Creacion de subconjuntos
ruta = "..\\data\\Crime_Data_from_2020_to_Present.csv"

df = pd.read_csv(ruta)
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468

In [4]:
df["Status Desc"].value_counts()

Status Desc
Invest Cont     605801
Adult Other      81519
Adult Arrest     66147
Juv Arrest        2391
Juv Other         1280
UNK                  3
Name: count, dtype: int64

# 3. Exploracion Inicial del Dataset

### tamaño de Dataset

In [158]:
df.shape

(757141, 28)

In [159]:
df.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='str')

### informacion del dataset

In [160]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 757141 entries, 0 to 757140
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           757141 non-null  int64
 1   Date Rptd       757141 non-null  str
 2   DATE OCC        757141 non-null  str
 3   TIME OCC        757141 non-null  int64
 4   AREA            757141 non-null  int64
 5   AREA NAME       757141 non-null  str
 6   Rpt Dist No     757141 non-null  int64
 7   Part 1-2        757141 non-null  int64
 8   Crm Cd          757141 non-null  int64
 9   Crm Cd Desc     757141 non-null  str
 10  Mocodes         653226 non-null  str
 11  Vict Age        757141 non-null  int64
 12  Vict Sex        658230 non-null  str
 13  Vict Descent    658224 non-null  str
 14  Premis Cd       757132 non-null  float64
 15  Premis Desc     756699 non-null  str
 16  Weapon Used Cd  263079 non-null  float64
 17  Weapon Desc     263079 non-null  str
 18  Status          757141 non-null  str
 19  Status Desc     757141 non-null  str
 20  Crm Cd 1        757131 non-null  float64
 21  Crm Cd 2        56016 non-null   float64
 22  Crm Cd 3        1872 non-null    float64
 23  Crm Cd 4        56 non-null      float64
 24  LOCATION        757141 non-null  str
 25  Cross Street    121732 non-null  str
 26  LAT             757141 non-null  float64
 27  LON             757141 non-null  float64
dtypes: float64(8), int64(7), str(13)
memory usage: 161.7 MB

### descripcion detallada de Dataset

In [161]:
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,7.571410e+05,757141.000000,757141.000000,757141.000000,757141.000000,757141.000000,757141.000000,757132.000000,263079.000000,757131.000000,56016.000000,1872.000000,56.000000,757141.000000,757141.000000
mean,2.148771e+08,1334.814871,10.718368,1118.245674,1.415613,500.847668,29.909412,305.938960,362.590230,500.589136,957.298861,983.676282,990.232143,33.971554,-117.999799
std,1.033130e+07,653.847053,6.092302,609.235556,0.492828,207.952490,21.731307,216.793004,123.737617,207.743554,111.871937,51.356926,28.834317,1.864571,6.465919
min,8.170000e+02,1.000000,1.000000,101.000000,1.000000,110.000000,-2.000000,101.000000,101.000000,110.000000,210.000000,434.000000,821.000000,0.000000,-118.667600
25%,2.021135e+08,900.000000,6.000000,622.000000,1.000000,331.000000,11.000000,101.000000,309.000000,331.000000,998.000000,998.000000,998.000000,34.013300,-118.429500
50%,2.119136e+08,1415.000000,11.000000,1142.000000,1.000000,442.000000,31.000000,203.000000,400.000000,442.000000,998.000000,998.000000,998.000000,34.058400,-118.321400
75%,2.215089e+08,1900.000000,16.000000,1618.000000,2.000000,626.000000,45.000000,501.000000,400.000000,626.000000,998.000000,998.000000,998.000000,34.163100,-118.273900
max,2.399165e+08,2359.000000,21.000000,2199.000000,2.000000,956.000000,120.000000,974.000000,516.000000,956.000000,999.000000,999.000000,999.000000,34.334300,0.000000

# 4.Limpieza

In [5]:
df.isnull().sum()

DR_NO                  0
Date Rptd              0
DATE OCC               0
TIME OCC               0
AREA                   0
AREA NAME              0
Rpt Dist No            0
Part 1-2               0
Crm Cd                 0
Crm Cd Desc            0
Mocodes           103915
Vict Age               0
Vict Sex           98911
Vict Descent       98917
Premis Cd              9
Premis Desc          442
Weapon Used Cd    494062
Weapon Desc       494062
Status                 0
Status Desc            0
Crm Cd 1              10
Crm Cd 2          701125
Crm Cd 3          755269
Crm Cd 4          757085
LOCATION               0
Cross Street      635409
LAT                    0
LON                    0
dtype: int64

## TRATAMIENTO DE NULOS
Se tratarán los nulos de las siguientes variables:``Mocodes``, ``Vict Sex``, ``Vict Descent``, ``Premis``, ``Weapon``, ``Crm``, ``Cross Street``

* ### Mocodes
Esta variable no aporta ninguna informacion crucial y menos aun para ser una predictiva, por lo tanto, nos desharemos de ella.

In [6]:
df=df.drop("Mocodes", axis=1)

* ### Sexo de la victima
la variable ``Vict Sex`` podria ser una columna feature, debido a que nos proporciona info de la victima.

In [7]:
df["Vict Sex"].value_counts()

Vict Sex
M    313598
F    279785
X     64759
H        87
-         1
Name: count, dtype: int64

Se puede ver los 3 tipos de valores con mayor demanda para esta variable, dichos tipos de variables hacen referencia al género masculino ,femenino y al desconocido, es decir, el PDLA(Police Department Los Angeles) ya tiene un carácter reservado para los géneros desconocidos, así es como trataremos los nulos, teniendo en cuenta también los otros tipos de valores los reemplazaremos por esta X

In [8]:
#Rellenamos valores nulos.
df["Vict Sex"]= df["Vict Sex"].fillna("X")

#Reemplazamos esos valores rarillos con pocas ocurrencias.
df["Vict Sex"]= df["Vict Sex"].replace(to_replace="[^MFX]", value="X", regex=True)

* ### Descendencia/etnia de la victima
la variable ``Vict Descent`` podria ser una columna feature, debido a que nos proporciona info de la victima.

In [9]:
df["Vict Descent"].value_counts()

Vict Descent
H    232578
W    155242
B    108667
X     71785
O     59910
A     16531
K      4031
F      3155
C      2846
J      1062
V       766
I       722
Z       370
P       207
U       157
D        52
G        51
L        47
S        43
-         2
Name: count, dtype: int64

De nuevo volvemos a tener un carácter reservado para aquellas descendencias desconocidas, al igual que hemos hecho para el sexo de la víctima se tratarán los nulos rellenándolos con dicho carácter.

In [10]:
#Rellenamos valores nulos.
df["Vict Descent"]= df["Vict Descent"].fillna("X")

#Reemplazamos esos valores raros con pocas ocurrencias.
df["Vict Descent"]= df["Vict Descent"].replace(to_replace="[-]", value="X", regex=True)

* ### Descripcion del lugar
la variable ``Premis`` podria ser una columna feature, debido a que nos proporciona info del contexto del crimen, para entrenar en concreto usaremos la variable ``Premis Cd`` que ya nos ahorra el trabajo de codificar una variable categorica.

In [22]:
df["Premis Cd"]=df["Premis Cd"].fillna(0)
df["Premis Desc"]=df["Premis Desc"].fillna("Unknown")

En este caso los nulos se rellenarán con un cero, porque tampoco es crucial esta info.

* ### Arma Usada
la variable ``Weapon`` podria ser una columna feature, debido a que nos proporciona info del contexto del crimen, en concreto usaremos la variable ``Weapon Used Cd`` que ya nos ahorra el trabajo de codificar una variable categorica.

In [13]:
df["Weapon Desc"].value_counts()

Weapon Desc
STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)    141322
UNKNOWN WEAPON/OTHER WEAPON                        27323
VERBAL THREAT                                      19409
HAND GUN                                           16320
SEMI-AUTOMATIC PISTOL                               6006
                                                   ...
MAC-11 SEMIAUTOMATIC ASSAULT WEAPON                    3
MAC-10 SEMIAUTOMATIC ASSAULT WEAPON                    2
M1-1 SEMIAUTOMATIC ASSAULT RIFLE                       1
HECKLER & KOCH 91 SEMIAUTOMATIC ASSAULT RIFLE          1
M-14 SEMIAUTOMATIC ASSAULT RIFLE                       1
Name: count, Length: 79, dtype: int64

Cómo se aprecia en la salida del código anterior podemos ver que hay un tipo de valor para la variable ``Weapon Desc`` que hace referencia a que no hay un arma o se trata de un arma desconocida, primero revelaremos a qué código de arma hace referencia está descripción y rellenaremos con este código todos los nulos de ``Weapon Used Cd`` interpretando así que se trata de casos en los que no se han registrado armas.

In [24]:
df["Weapon Desc"]=df["Weapon Desc"].fillna("UNKNOWN WEAPON/OTHER WEAPON")

In [20]:
codeDesconocido=float(df.loc[
df["Weapon Desc"]=="UNKNOWN WEAPON/OTHER WEAPON", "Weapon Used Cd"
].iloc[0])
df["Weapon Used Cd"]=df["Weapon Used Cd"].fillna(codeDesconocido)

* ### Delitos
La variable ``Crm`` podria ser una columna feature debido a que nos informa del tipo de crimen, dado que se nos proporciona tanto el delito principal(``Crm Cd Desc``, ``Crm Cd`` y ``Crm Cd 1``) como los delitos secundarios(``Crm Cd 2``, ``Crm Cd 3``,``Crm Cd 4``), para el primer crimen usaremos la variable ``Crm Cd`` que ya nos ahorra el trabajo de codificar una variable categorica 
> para el delito principal a pesar de que tenemos otra variable que nos da la misma informacion ``Crm Cd 1`` se ha elegido la que no tiene nulos.

para los casos secundarios se usaran los tres que aportan informacion de los delitos adicionales: ``Crm Cd 2``, ``Crm Cd 3``,``Crm Cd 4``

Por lo tanto se eliminarán dichas variables que aportan información duplicada o no codificada.

In [21]:

df=df.drop(columns=["Crm Cd 1"])

KeyError: "['Crm Cd 1'] not found in axis"

Al igual que en el caso de la descripción del lugar(``Premis Cd``) se rellenarán los nulos con un código **0** interpretando así que no ha habido crímenes secundarios.

In [16]:
df["Crm Cd 2"]=df["Crm Cd 2"].fillna(0)
df["Crm Cd 3"]=df["Crm Cd 3"].fillna(0)
df["Crm Cd 4"]=df["Crm Cd 4"].fillna(0)

* ### Calle transversal
la variable ``Cross Street`` según el departamento de policía de Los Ángeles(LAPD) busca dar una información más precisa acerca de la localización, es decir, además de la dirección de la calle(``Location``) también se da la calle que intersecta con ella, en nuestro caso ya tenemos suficiente con la información de la principal, por lo tanto dicha variable es irrelevante para el entrenado del modelo.

In [17]:
df=df.drop("Cross Street", axis=1)

> Y finalmente asi es como se nos queda la tabla de nulos:

In [25]:
df.isnull().sum()

DR_NO             0
Date Rptd         0
DATE OCC          0
TIME OCC          0
AREA              0
AREA NAME         0
Rpt Dist No       0
Part 1-2          0
Crm Cd            0
Crm Cd Desc       0
Vict Age          0
Vict Sex          0
Vict Descent      0
Premis Cd         0
Premis Desc       0
Weapon Used Cd    0
Weapon Desc       0
Status            0
Status Desc       0
Crm Cd 2          0
Crm Cd 3          0
Crm Cd 4          0
LOCATION          0
LAT               0
LON               0
dtype: int64

In [26]:
df.shape[0]

757141

# 5.Preparado datos

## Categorias a usar
vamos a terminar de definir cuales van a ser las variables predictorias

### Variables Categoricas
de las siguientes variables categoricas:``Date Rptd``, ``DATE OCC``, ``AREA NAME``, ``Vict Sex``, ``Vict Descent``, ``Status``, ``LOCATION``, ``Status Desc``:
prescindiremos de
* **Date Rptd:** indica cuando se denunció o informó.
* **Status:** revela la misma informacion que ``Status Desc`` pero representado de distinta manera.

In [27]:
df= df.drop(columns=["Status", "Date Rptd"])

### Variables Númericas
de las siguientes variables númericas:``DR_NO``, ``TIME OCC``, ``AREA``, ``Rpt Dist No``, ``Part 1-2``, ``Crm Cd``, ``Vict Age``, ``Premis Cd``, ``Weapon Used Cd``, ``Crm Cd 2``, ``Crm Cd 3``, ``Crm Cd 4``, ``LAT``, ``LON``:
prescindiremos de

* **LAT:** descripcion demasiado precisa, es parte de una coordenada.
* **LON:** descripcion demasiado precisa, es parte de una coordenada.

In [28]:
df=df.drop(columns=["LAT", "LON"])

## Adecuando variables

### Numéricas

In [29]:
#adecuando a tipos numericas
df["Premis Cd"]=df["Premis Cd"].astype(int)
df["Weapon Used Cd"]=df["Weapon Used Cd"].astype(int)
df["Crm Cd 2"]=df["Crm Cd 2"].astype(int)
df["Crm Cd 3"]=df["Crm Cd 3"].astype(int)
df["Crm Cd 4"]=df["Crm Cd 4"].astype(int)

### Edad

In [32]:
df[df["Vict Age"]<0].shape[0]

59

Cómo se puede comprobar hay 59 registros con la edad en número negativo, en un dataset de 750.000 registros es una cantidad totalmente irrelevante que puede ser eliminada

In [33]:
df=df[df["Vict Age"]>=0]

In [34]:
df["Vict Age"].describe()

count    757082.000000
mean         29.911835
std          21.730419
min           0.000000
25%          11.000000
50%          31.000000
75%          45.000000
max         120.000000
Name: Vict Age, dtype: float64

Ahora cómo se puede ver el valor mínimo es el cero representando meses

### Location

In [184]:
df["LOCATION"].head(n=25)

0      1100 W  39TH                         PL
1       700 S  HILL                         ST
2       200 E  6TH                          ST
3      5400    CORTEEN                      PL
4     14400    TITUS                        ST
5                              700 S  BROADWAY
6       700 S  FIGUEROA                     ST
7       200 E  6TH                          ST
8       700    BERNARD                      ST
9     11900    BALBOA                       BL
10                                        15TH
11      800 N  ALAMEDA                      ST
12      800 S  OLIVE                        ST
13      700 W  7TH                          ST
14      100 S  LOS ANGELES                  ST
15    14200    BERG                         ST
16                           3200 W  AVENUE 32
17                               PACIFIC COAST
18    14700    FRIAR                        ST
19                                         7TH
20    13600    LEADWELL                     ST
21      700 W  7TH                          ST
22      700 W  7TH                          ST
23     5700    ENFIELD                      AV
24      600    SAN JULIAN                   ST
Name: LOCATION, dtype: str

Recordando que estos datos van a ser usados para entrenar un modelo conviene adecuar los datos de location, dado que, tienen una cantidad de espacios qué no tiene sentido y a la hora de intentar predecir si no pasamos para el valor de location la cantidad exacta de espacios, el encoder no funcionará, por lo tanto es de vital importancia adecuar esto.

In [35]:
df["LOCATION"]=df["LOCATION"].replace(r'\s+', ' ', regex=True)

In [36]:
df["LOCATION"].head(n=25)

0           1100 W 39TH PL
1            700 S HILL ST
2             200 E 6TH ST
3          5400 CORTEEN PL
4           14400 TITUS ST
5           700 S BROADWAY
6        700 S FIGUEROA ST
7             200 E 6TH ST
8           700 BERNARD ST
9          11900 BALBOA BL
10                    15TH
11        800 N ALAMEDA ST
12          800 S OLIVE ST
13            700 W 7TH ST
14    100 S LOS ANGELES ST
15           14200 BERG ST
16        3200 W AVENUE 32
17           PACIFIC COAST
18          14700 FRIAR ST
19                     7TH
20       13600 LEADWELL ST
21            700 W 7TH ST
22            700 W 7TH ST
23         5700 ENFIELD AV
24       600 SAN JULIAN ST
Name: LOCATION, dtype: str

ahora queda mejor

### Variable objetivo

In [187]:
df["Status Desc"].value_counts()

Status Desc
Invest Cont     605746
Adult Other      81516
Adult Arrest     66146
Juv Arrest        2391
Juv Other         1280
UNK                  3
Name: count, dtype: int64

In [37]:
df["Status Desc"]=df["Status Desc"].replace(to_replace="UNK", value="Invest Cont")
df["Status Desc"].value_counts()

Status Desc
Invest Cont     605749
Adult Other      81516
Adult Arrest     66146
Juv Arrest        2391
Juv Other         1280
Name: count, dtype: int64

de esta manera terminamos de aclarar los posibles valores de la variable objetivo, aunque mas adelante se codificará([Adult arrest, juv arrest]=1, Adult other, [juv other]=0)

### Delitos secundarios

Algo que no encaja en este dataset es que el delito principal tiene una referencia descriptiva, es decir, Crm Cd -> Crm Cd Desc pero los secundarios no cuentan con esa suerte, por lo tanto trataremos de crear su referencia descriptiva y lo rellenaremos apartir de un mapeador

In [ ]:
mapeadorCrm=df[["Crm Cd", "Crm Cd Desc"]]

mapeadorCrm=mapeadorCrm.drop_duplicates().dropna()

np.int64(0)

una vez lo hemos creado vamos a darle uso

In [39]:
df["Crm Cd 2 Desc"] = df["Crm Cd 2"].map(
    mapeadorCrm.set_index("Crm Cd")["Crm Cd Desc"]
)

In [40]:
df[["Crm Cd 2 Desc", "Crm Cd 2"]].dropna().head()

                                         Crm Cd 2 Desc  Crm Cd 2
17                            BATTERY - SIMPLE ASSAULT       624
54                            BATTERY - SIMPLE ASSAULT       624
109  CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...       812
221                        BATTERY WITH SEXUAL CONTACT       860
292                  INTIMATE PARTNER - SIMPLE ASSAULT       626

In [41]:
df["Crm Cd 3 Desc"] = df["Crm Cd 3"].map(
    mapeadorCrm.set_index("Crm Cd")["Crm Cd Desc"]
)

In [42]:
df[["Crm Cd 3 Desc", "Crm Cd 3"]].dropna().shape[0]

211

In [43]:
df["Crm Cd 4 Desc"] = df["Crm Cd 4"].map(
    mapeadorCrm.set_index("Crm Cd")["Crm Cd Desc"]
)

In [44]:
df[["Crm Cd 4 Desc", "Crm Cd 4"]].dropna().head()

                                            Crm Cd 4 Desc  Crm Cd 4
50299              CRIMINAL THREATS - NO WEAPON DISPLAYED       930
91248   SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO...       821
234389                                         KIDNAPPING       910
492571                          OTHER MISCELLANEOUS CRIME       946
698103                          OTHER MISCELLANEOUS CRIME       946

In [196]:
df.info()

<class 'pandas.DataFrame'>
Index: 757082 entries, 0 to 757140
Data columns (total 24 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           757082 non-null  int64
 1   DATE OCC        757082 non-null  str
 2   TIME OCC        757082 non-null  int64
 3   AREA            757082 non-null  int64
 4   AREA NAME       757082 non-null  str
 5   Rpt Dist No     757082 non-null  int64
 6   Part 1-2        757082 non-null  int64
 7   Crm Cd          757082 non-null  int64
 8   Crm Cd Desc     757082 non-null  str
 9   Vict Age        757082 non-null  int64
 10  Vict Sex        757082 non-null  str
 11  Vict Descent    757082 non-null  str
 12  Premis Cd       757082 non-null  int64
 13  Premis Desc     756640 non-null  str
 14  Weapon Used Cd  757082 non-null  int64
 15  Weapon Desc     263075 non-null  str
 16  Status Desc     757082 non-null  str
 17  Crm Cd 2        757082 non-null  int64
 18  Crm Cd 3        757082 non-null  int64
 19  Crm Cd 4        757082 non-null  int64
 20  LOCATION        757082 non-null  str
 21  Crm Cd 2 Desc   10980 non-null   str
 22  Crm Cd 3 Desc   211 non-null     str
 23  Crm Cd 4 Desc   5 non-null       str
dtypes: int64(12), str(12)
memory usage: 144.4 MB

In [45]:
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 2,Crm Cd 3,Crm Cd 4
count,7.570820e+05,757082.000000,757082.000000,757082.000000,757082.000000,757082.000000,757082.000000,757082.000000,757082.000000,757082.000000,757082.000000,757082.000000
mean,2.148763e+08,1334.836184,10.718312,1118.240018,1.415590,500.841143,29.911835,305.926630,452.252121,70.829914,2.432289,0.073246
std,1.033108e+07,653.843689,6.092307,609.235977,0.492824,207.950215,21.730419,216.790768,97.987095,252.417488,48.920242,8.519705
min,8.170000e+02,1.000000,1.000000,101.000000,1.000000,110.000000,0.000000,0.000000,101.000000,0.000000,0.000000,0.000000
25%,2.021135e+08,900.000000,6.000000,622.000000,1.000000,331.000000,11.000000,101.000000,400.000000,0.000000,0.000000,0.000000
50%,2.119136e+08,1415.000000,11.000000,1142.000000,1.000000,442.000000,31.000000,203.000000,500.000000,0.000000,0.000000,0.000000
75%,2.215088e+08,1900.000000,16.000000,1618.000000,2.000000,626.000000,45.000000,501.000000,500.000000,0.000000,0.000000,0.000000
max,2.399165e+08,2359.000000,21.000000,2199.000000,2.000000,956.000000,120.000000,974.000000,516.000000,999.000000,999.000000,999.000000

In [198]:
df.shape

(757082, 24)

# Exportacion
Exportamos del dataset limpio un subconjunto **crimeData_subconjunto_NoInvestigacion_Train.csv** que se usará para entrenar el modelo y **crimeData_limpio.csv**

teniendo en cuenta que tambien se va a predecir a partir de los registros en estado de investigacion del dataset **CrimeData_limpio**, con el objetivo de evitar extrapolaciones y que a la hora de codificar los datos a predecir surgan problemas, se va a analizar que no hayan mas tipos de datos a predecir que los que se van a usar para entrenar el modelo y se aplicará un filtrado sobre todas las dichas variables predictivas.

> en realidad se podría eliminar esta discordancia de tipo de valores para las variables categóricas dado que serán las que sí o sí dará darán un error al pasarlo por los encoders pero ya que estamos también se limitarán las variables numéricas

## Solucionando problemas de tipo de valores

In [51]:
df.nunique()

DR_NO             663210
DATE OCC            1286
TIME OCC            1429
AREA                  21
AREA NAME             21
Rpt Dist No         1151
Part 1-2               2
Crm Cd               129
Crm Cd Desc          129
Vict Age              99
Vict Sex               3
Vict Descent          18
Premis Cd            278
Premis Desc          275
Weapon Used Cd        75
Weapon Desc           75
Status Desc            5
Crm Cd 2              91
Crm Cd 3              26
Crm Cd 4               4
LOCATION           32848
Crm Cd 2 Desc         78
Crm Cd 3 Desc         21
Crm Cd 4 Desc          2
dtype: int64

estos son los tipos de valores para todos los casos incluidos los que estan en investigacion.

In [47]:
dfnoInvestigacion=df[df["Status Desc"]!="Invest Cont"]
dfnoInvestigacion.nunique()

DR_NO             151333
DATE OCC            1286
TIME OCC            1429
AREA                  21
AREA NAME             21
Rpt Dist No         1151
Part 1-2               2
Crm Cd               129
Crm Cd Desc          129
Vict Age              99
Vict Sex               3
Vict Descent          18
Premis Cd            278
Premis Desc          275
Weapon Used Cd        75
Weapon Desc           75
Status Desc            4
Crm Cd 2              91
Crm Cd 3              26
Crm Cd 4               4
LOCATION           32848
Crm Cd 2 Desc         78
Crm Cd 3 Desc         21
Crm Cd 4 Desc          2
dtype: int64

y estos los tipos para los casos que ya han tenido una resolucion.

In [48]:
df.shape[0]

757082

In [49]:
df=df[df["DATE OCC"].isin(dfnoInvestigacion["DATE OCC"])]
df=df[df["TIME OCC"].isin(dfnoInvestigacion["TIME OCC"])]
df=df[df["AREA"].isin(dfnoInvestigacion["AREA"])]
df=df[df["Rpt Dist No"].isin(dfnoInvestigacion["Rpt Dist No"])]
df=df[df["Part 1-2"].isin(dfnoInvestigacion["Part 1-2"])]
df=df[df["Crm Cd"].isin(dfnoInvestigacion["Crm Cd"])]
df=df[df["Vict Age"].isin(dfnoInvestigacion["Vict Age"])]
df=df[df["Vict Sex"].isin(dfnoInvestigacion["Vict Sex"])]
df=df[df["Vict Descent"].isin(dfnoInvestigacion["Vict Descent"])]
df=df[df["Premis Cd"].isin(dfnoInvestigacion["Premis Cd"])]
df=df[df["Weapon Used Cd"].isin(dfnoInvestigacion["Weapon Used Cd"])]
df=df[df["Crm Cd 2"].isin(dfnoInvestigacion["Crm Cd 2"])]
df=df[df["Crm Cd 3"].isin(dfnoInvestigacion["Crm Cd 3"])]
df=df[df["Crm Cd 4"].isin(dfnoInvestigacion["Crm Cd 4"])]
df=df[df["LOCATION"].isin(dfnoInvestigacion["LOCATION"])]

In [50]:
df.shape[0]

663210

Una vez aplicado el filtrado de tipo de valores se han reducido casi 100.000 valores

el subconjunto que se usará para el entrenado, no contará con la siguientes variables:
* **LOCATION:**
* **DR_NO:** es un simple identificador.

y todas las variables descriptivas que tienen una variable codificada.

de esta manera nos quedan los siguientes campos para entrenar el modelo:
* **informacion Crimen**:
  -  **Cuando:** ``DATE OCC``, ``TIME OCC``
  -  **Donde:** ``AREA``(Barrio), ``Rpt Dist No``(Nº sector de barrio), ``LOCATION``(calle), ``Premis Cd``(descripcion de lugar)
  -  **Que:** ``Crm Cd``, ``Crm Cd 2``, ``Crm Cd 3``, ``Crm Cd 4``
  -  **Otra Info:** ``Part 1-2``(Nivel importancia de delito), ``Weapon Used Cd``(Cod de arma usada), ``Status Desc``(variable objetivo|arrestado/no arrestado)

* **informacion de Victima**
  - ``Vict Age``(edad de la victima)
  - ``Vict Sex``(sexo de la victima)
  - ``Vict Descent``(descendiencia/etnia de la victima)

Ahora podemos exportar para el entrenado y el dataset original filtrado, que tambien servirá para predecir por id.

In [52]:
dfnoInvestigacion.drop(columns=["Premis Desc", "Weapon Desc", "Crm Cd Desc", "Crm Cd 2 Desc", "Crm Cd 3 Desc", "Crm Cd 4 Desc", "AREA NAME", "DR_NO", "LOCATION"]).to_csv("..\\data\\crimeData_subconjunto_no_Investigacion_train.csv")
df.to_csv("..\\data\\crimeData_limpio.csv")